import Head from "next/head";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import ArrowDownIcon from "@mui/icons-material/ArrowDownward";
import { IconButton } from "@mui/material";
import theme from "../src/theme";
import { motion } from "framer-motion";

const Home = ({ props }) => {
	return (
		<Container maxWidth="lg">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box
				className="main-container"
				sx={{
					display: "flex",
					flexDirection: "column",
					height: "100vh",
					justifyContent: "center",
					alignItems: "center",
					backgroundColor: theme.palette.primary.highlight,
				}}
			>
				<h1 style={{ color: theme.palette.primary.main }}>
					Welcome to lyrics grabber!
				</h1>

				<motion.div
					animate={{ y: ["10%", "-10%"] }}
					transition={{
						y: {
							duration: 0.4,
							yoyo: Infinity,
							ease: "easeOut",
						},
					}}
				>
					<IconButton aria-label="delete" color="primary" size="large">
						<ArrowDownIcon fontSize="inherit" />
					</IconButton>
				</motion.div>
			</Box>
		</Container>
	);
};

export default Home;
